### ISSUE TITLE
Bug: Incompatibility with Border-Control

### ISSUE THREAD

**Issue by Merudo** [sPOiDar/fvtt-module-better-target#4]
When the module [Border Control](https://github.com/kandashi/Border-Control) is enabled, `Better Target` doesn't work. The following error is generated:

```
VM1519:8 U: Conflict detected between module 'better-target' and module 'Border-Control'.
Failed to wrap 'Token.prototype._refreshTarget' for module 'better-target' with type OVERRIDE. An OVERRIDE wrapper for the same method has already been registered by module 'Border-Control'.
    at Function.🎁register [as register] (https://localhost:3003/modules/lib-wrapper/lib-wrapper.js:1:30123)
    at https://localhost:3003/modules/better-target/modules/better_target.js:10:13
    at Function._call (eval at <anonymous> (https://localhost:3003/modules/lib-wrapper/lib-wrapper.js:1:33400), <anonymous>:4:14)
    at Function.callAll (https://localhost:3003/scripts/foundry.js:153:12)
    at Game.setupGame (https://localhost:3003/scripts/foundry.js:4307:11)
    at async Game._initializeGameView (https://localhost:3003/scripts/foundry.js:5117:5)
    at async Game.initialize (https://localhost:3003/scripts/foundry.js:4202:5)
```

**Comment by Merudo** [comment]
Link to Border Control issue: https://github.com/kandashi/Border-Control/issues/34

**Comment by sPOiDar** [comment]
I'm not certain why Border Control hooks this method, but it has a setting you can turn off to stop this conflict that specifically mentions Better Target in its description.
